openapi: 3.0.0
info:
  title: Petstore - OpenAPI 3.0
  version: "0.1"

servers:
  - url: http://localhost:3001

paths:
  "/pet/{petId}":
    get:
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          $ref: "#/components/responses/200"
        "404":
          $ref: "#/components/responses/404"
      security:
        - bearer: []
      x-ft-security:
        authenticated-principal-path: user.userId
        resource-authorised-principal-path: ownerId
        # access-resolver: petAccessByTag
      x-ft-sensitive-headers:
        - postman-token
  /pet/add:
    post:
      operationId: addPet
      responses:
        "200":
          $ref: "#/components/responses/200"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      security:
        - bearer: ["write"]
      x-ft-security:
        authenticated-principal-path: user.userId
      x-ft-sensitive-headers:
        - postman-token

components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: UUID
  schemas:
    Tag:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Pet:
      additionalProperties: false
      required:
        - name
        - id
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          pattern: ^(dog|cat)$
          example: dog
        tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
  responses:
    "200":
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Pet"
    "404":
      description: Request failed
      content:
        text/plain:
          schema:
            type: string
