openapi: 3.0.0
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: "0.1"
  description: This is a sample Pet Store Server based on the OpenAPI 3.0 spec.

servers:
  - url: http://localhost:3001

paths:
  "/pet/{petId}/get-with-tag-based-auth":
    get:
      summary: Find pet with tag based authorisation
      description: Returns a single pet is user has access to any of pet's tags
      operationId: getPetById
      parameters:
        - name: petId
          in: path
          description: ID of pet to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          $ref: "#/components/responses/200"
        "404":
          $ref: "#/components/responses/404"
      security:
        - jwt: []
      x-ft-security:
        access-resolver: petAccessByTag
        authenticated-principal-path: user.userId

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Tag:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Pet:
      additionalProperties: false
      required:
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          pattern: (dog|cat)
          example: doggie
        tags:
          type: array
          items:
            $ref: "#/components/schemas/Tag"
  responses:
    "200":
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Pet"
    "404":
      description: Request failed
      content:
        text/plain:
          schema:
            type: string
