service: js-serverless-test-1
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

functions:
  listpets:
    handler: store.listpets
    events:
      - http:
          path: /pets
          method: get
  addpets:
    handler: store.addpets
    events:
      - http:
          path: /pets
          method: post
          response:
            headers:
              Content-Type: "'application/xml'"
