service: js-serverless-test-1
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-offline

functions:
  pets:
    handler: handler.pets
    events:
      - httpApi:
          path: /pets
          payloadVersion: '1.0'
          method: get
      - http:
          path: /pets
          method: get
